version: "2.4"

services:
  neural-astar:
    image: omron-sinicx/neural-astar:minimal
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    container_name: myuser.neural-astar
    volumes:
      - C:\Users\mirza\ASU\MS_master_folder\semester_3\perceptionRobotics\baseLines\neural-astar:/workspace
    environment:
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - 8888
      - 6666
    command: bash
    tty: true